apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-03-26T23:15:13Z"
  generation: 5
  labels:
    app: go-get-mtg-prices
  name: go-get-mtg-prices
  namespace: default
  resourceVersion: "25491621"
  selfLink: /apis/apps/v1/namespaces/default/deployments/go-get-mtg-prices
  uid: 5a2947f3-0e48-4da8-9d5b-d505c368faae
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-get-mtg-prices
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-get-mtg-prices
    spec:
      containers:
      - image: us.gcr.io/ci-cd-263902/go-get-mtg-prices@sha256:c65de22bc05e4b17f7773abdd7d73f5eb1f8a359ac9c9b86911484a82cd7f5f2
        imagePullPolicy: IfNotPresent
        name: go-get-mtg-prices-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumes:
        - name: card-list-configmap
          configMap:
            name: card-list-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-03-26T23:37:31Z"
    lastUpdateTime: "2020-03-26T23:37:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-26T23:15:13Z"
    lastUpdateTime: "2020-03-26T23:45:23Z"
    message: ReplicaSet "go-get-mtg-prices-699b759ff7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
